require 'rubygems'
require 'test/unit'
require File.dirname(__FILE__) + '/../lib/active_node'
require File.dirname(__FILE__) + '/../lib/active_node/test_helper'
require 'shoulda'
require 'pp'
require 'mocha'
